#### Absenteeism Module testing file 

    creating a module with methods
    
        1. load_clean_data  - loads the new data and cleans it along with scaling
        2. predicted_probability - gets the probability for each record
        3. predicted_output_category - gets the predited value 
        4. predicted_outputs - displays the dataframe with probability and prediction
        5. __init__

In [2]:
from Absenteeism_module import *

In [3]:

# getting the new data and cleaning 
new_data = 'data_raw_new.xls'


ab_mod = Absenteeism_module()


ab_mod.load_n_clean(new_data)

cleaned_data = ab_mod.data 
cleaned_data.head()

,Reason_1,Reason_2,Reason_3,Reason_4,Month of absence,Day of the week,Transportation expense,Distance from Residence to Work,Work load Average/day,Education,Son,Pet,Body mass index,Excessive Absentise
0,False,False,False,True,7,3,289,36,239554,0,2,1,30,1
1,False,False,False,False,7,3,118,13,239554,0,1,0,31,0
2,False,False,False,True,7,4,179,51,239554,0,0,0,31,0
3,True,False,False,False,7,5,279,5,239554,0,2,0,24,1
4,False,False,False,True,7,5,289,36,239554,0,2,1,30,0

# Scaling the data

In [6]:
columns_to_scale = ['Month of absence',
            'Day of the week', 'Transportation expense',
            'Distance from Residence to Work', 'Work load Average/day ','Son', 'Pet', 'Body mass index']
cus_scale = CustomScaler(columns_to_scale)

scaled_data = cus_scale.fit_transform(cleaned_data)
scaled_data.head()

,Reason_1,Reason_2,Reason_3,Reason_4,Month of absence,Day of the week,Transportation expense,Distance from Residence to Work,Work load Average/day,Education,Son,Pet,Body mass index,Excessive Absentise
0,False,False,False,True,0.23857,-0.642974,1.108483,0.468624,-0.766302,0,1.137446,0.089864,0.598627,1
1,False,False,False,False,0.23857,-0.642974,-1.551082,-1.111977,-0.766302,0,0.073566,-0.585910,0.813813,0
2,False,False,False,True,0.23857,0.059812,-0.602348,1.499451,-0.766302,0,-0.990314,-0.585910,0.813813,0
3,True,False,False,False,0.23857,0.762597,0.952953,-1.661752,-0.766302,0,1.137446,-0.585910,-0.692485,1
4,False,False,False,True,0.23857,0.762597,1.108483,0.468624,-0.766302,0,1.137446,0.089864,0.598627,0

In [7]:
output = ab_mod.predicted_outputs(scaled_data.iloc[:,:-1])

In [8]:
((scaled_data['Excessive Absentise'] == output['Prediction']).sum())/ ((scaled_data['Excessive Absentise'] == output['Prediction']).count())

0.9148936170212766

# 91% of the time our model is predicting the "Excessive Absentise"